set(SAKURA_EXECUTABLE sakura)
project(${SAKURA_EXECUTABLE})

# SET LIBRARY PATH
set(LIBSAKURA_HOME "${PROJECT_SOURCE_DIR}/src/sakura")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

set(CMAKE_C_FLAGS_DEBUG "-O -g")
set(CMAKE_CXX_FLAGS_DEBUG "-O -g")
if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fsanitize=address")
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=address")
endif()

set(SOURCE_FILES ${LIBSAKURA_HOME}/Sakura.cpp ${LIBSAKURA_HOME}/main.cpp)
include_directories(${LIBSAKURA_HOME} ${THIRDPARTY_INCLUDE_PATH})

add_executable(${SAKURA_EXECUTABLE} ${SOURCE_FILES})
add_dependencies(${SAKURA_EXECUTABLE} LIBJPEGTURBO LIBWEBP GIFLIB FFMPEG ZLIB LIBPNG)
link_directories(${THIRDPARTY_LIBRARY_PATH})
target_link_libraries(${SAKURA_EXECUTABLE}
  ${THIRDPARTY_LIBRARY_PATH}/libgif.a
  ${THIRDPARTY_LIBRARY_PATH}/libjpeg.a
  ${THIRDPARTY_LIBRARY_PATH}/libturbojpeg.a
  ${THIRDPARTY_LIBRARY_PATH}/libz.a
  ${THIRDPARTY_LIBRARY_PATH}/libpng.a
  ${THIRDPARTY_LIBRARY_PATH}/libwebp.a
  ${THIRDPARTY_LIBRARY_PATH}/libavutil.a
  ${THIRDPARTY_LIBRARY_PATH}/libswscale.a
)
