set(SAKURA_EXECUTABLE sakura)
project(${SAKURA_EXECUTABLE})

# SET LIBRARY PATH
set(LIBSAKURA_HOME "${PROJECT_SOURCE_DIR}/src/sakura")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

set(SOURCE_FILES ${LIBSAKURA_HOME}/Sakura.cpp ${LIBSAKURA_HOME}/main.cpp)
include_directories(${LIBSAKURA_HOME} ${GIFLIB_HOME}/lib ${LIBWEBP_HOME}/src ${ZLIB_HOME} ${LIBPNG_HOME} ${LIB_MOZ_JPEG_TURBO_HOME})

add_executable(${SAKURA_EXECUTABLE} ${SOURCE_FILES})
add_dependencies(${SAKURA_EXECUTABLE} ${GIF_LIBRARY} ${WEBP_LIBRARY} ${PNG_LIBRARY} ${MOZ_JPEG_LIBRARY} ${MOZ_TURBO_JPEG_LIBRARY})
link_directories(${THIRDPARTY_LIBRARY_PATH})
target_link_libraries(${SAKURA_EXECUTABLE}
  ${THIRDPARTY_LIBRARY_PATH}/libgif.a
  ${THIRDPARTY_LIBRARY_PATH}/libgif.a
  ${THIRDPARTY_LIBRARY_PATH}/libjpeg.a
  ${THIRDPARTY_LIBRARY_PATH}/libz.a
  ${THIRDPARTY_LIBRARY_PATH}/libpng.a
  ${THIRDPARTY_LIBRARY_PATH}/libwebp.a
  avutil
  swscale
)

